# Generated by Django 3.1.7 on 2021-03-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='empresas',
            field=models.ManyToManyField(related_name='funcionarios', to='empresas.Empresa'),
        ),
    ]
